version: '3.1'
services:
  web:
    build: .
    image: gowebapp
    restart: always
    ports:
      - 8080:8080
  db:
    image: postgres:12.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: noteBookApp
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

